# Generated by Django 3.0.4 on 2020-03-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Name',
            field=models.TextField(max_length=10),
        ),
    ]
