# Generated by Django 3.0.2 on 2020-03-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200318_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='form',
            name='published_date',
        ),
    ]
