# Generated by Django 3.0.4 on 2020-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20200322_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='College_Name',
            field=models.TextField(null=True),
        ),
    ]
