# Generated by Django 3.0.4 on 2020-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20200322_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
